version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: "PassW0rd1"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    networks:
      - sql-network
    volumes:
      - sqldata:/var/opt/mssql
      - sqllog:/var/opt/sqlserver
networks:
  sql-network:
volumes:
  sqldata:
  sqllog:
